#!/bin/sh

# External SD scaffolding
if mount|grep -q /media/sdcard
then
    for dir in apps roms roms/32X roms/3DO roms/A2600 roms/A5200 roms/A7800      \
           roms/AMIGA roms/AMSTRAD roms/ARCADE roms/C64 roms/COLECO roms/CPS     \
           roms/DAPHNE roms/DOOM roms/DOSBOX roms/FBA roms/FC roms/GB            \
           roms/GBA roms/GBC roms/GG roms/GW roms/INTELLI roms/LYNX roms/MD      \
           roms/MSX roms/N64 roms/NEOGEO roms/NGP roms/PCE roms/PCECD            \
           roms/PICO8 roms/POKEMINI roms/PS roms/QUAKE roms/SCUMMVM              \
           roms/SEGACD roms/SFC roms/SMS roms/TIC80 roms/VB roms/VECTREX         \
           roms/WSC roms/ZX OpenBOR OpenBOR/Paks
    do
      if [ ! -d "/media/sdcard/${dir}" ]; then
        mkdir -p "/media/sdcard/${dir}"
      fi
    done
fi

# Ask for default launcher
opkrun /media/data/apps/launchsel.opk
